### ISSUE TITLE
Add the possibiliy to use username if src is false or null

### ISSUE THREAD

**Issue by kevingermain** [eliep/vue-avatar#24]
It could be nice if you can add the feature like if src is null or false, show the username by default. Typical case when someone didn't upload an avatar yet, the src still null so we should use his username (today, we have _"width: 64px; height: 64px; background: url("null") no-repeat;"_ and I don't want to use double "v-if" with double `"<avatar>"`

**Comment by saintplay** [comment]
This is the default expected behaviour. Can you replicate your problem in a sandbox please?

**Comment by saintplay** [comment]
Closed due inactivity

**Comment by packytagliaferro** [comment]
I currently have this same issue:
`<avatar username="{{ Auth::user()->first_name }} {{ Auth::user()->last_name }}" class="dealer-header-avatar" :size="30"	src=" {{ Auth::user()->avatar }} ">` 

this should show the username since the avatar is NULL in the database but it just shows a blank photo with:

`    background: url( ) 0% 0% / 30px 30px no-repeat scroll content-box border-box transparent;
}`

**Comment by saintplay** [comment]
![image](https://user-images.githubusercontent.com/9372893/40636028-acf4329a-62c2-11e8-8fda-5b2da563395d.png)


is working for me

**Comment by packytagliaferro** [comment]
@saintplay ya, its working for me now too. Not sure why it wasnt before
