### ISSUE TITLE
Better Responsive Support

### ISSUE THREAD

**Issue by zek** [eliep/vue-avatar#46]
First of all I don't have any issues, I just wanna explain my situation and how I solved it and maybe you have better idea and might merge this.

Right now I've applied some patches in order to use vue-avatar in card designs as width: 100% property. If I just set width: 100%, then height will be equal to default size. What I need was a fixed 1:1 ratio so I found out https://www.w3schools.com/howto/howto_css_aspect_ratio.asp

![image](https://user-images.githubusercontent.com/3463291/53348486-2e524a80-392c-11e9-848c-873b2d833513.png)

~~~
    <avatar :username="group.name"
            class="card-img-top"
            :customStyle="{width: '100%', height:null, 'padding-top': '100%', 'position' : 'relative'}"
            :src="group.photo_url"
            :rounded="false"
    />
~~~

![image](https://user-images.githubusercontent.com/3463291/53348451-580b7180-392c-11e9-9579-e4b339905ab8.png)

I applied and it is working. Now there is another problem. Span is not centered. This is what I did to make it centered.

~~~
.vue-avatar--wrapper span{
    display: flex;
    align-items: center;
    justify-content: center;
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
}
~~~

I am not a CSS expert. I am just a beginner and all I want is to use this library anywhere I want easily without problem. So this is my solution. 

Final Result is

![image](https://user-images.githubusercontent.com/3463291/53347814-f0a0f200-392a-11e9-9dbd-fd07e49356ea.png)

![image](https://user-images.githubusercontent.com/3463291/53348544-46c26500-392c-11e9-885e-280ce6128161.png)

What do you think?

**Comment by zek** [comment]
Maybe we can add a ratio prop so we can set padding-top part by given ratio

**Comment by saintplay** [comment]
Hi, thanks for bringing this up

First of all I do think, the styling of this component needs a cleanup, e.g. both `flex` and `line-height` are trying to do the vertical centering here.

Now, talking about the aspect ratio, or whatever size of the box. I think the best solution here is to make those dimensions in a wrapper `div`, and then just apply width and height to 100%.

Something like this:

```vue
<div style="width="100%; height:null; padding-top:100%">
    <avatar :username="group.name"
            :customStyle="{width: 100%;height:100%"}"
            :src="group.photo_url"
            :rounded="false"
    />
</div>

```

I would rather not add any styling related prop, since the CustomStyle should be enough, and we should do any complicated styling in a wrapper element, like the example above
